### ISSUE TITLE
The correspondence of day-twilight-night images

### ISSUE THREAD

**Issue by creater-zq** [sakaridis/MGCDA#3]
Hello, thanks!
- I want to train my network with day, twilight, and night images at the same time, but the day/twilight/night images are not one-to-one in the Dark Zurich dataset.  Do you have the corresponding relation table or list?  
- For example, in the image below, I **can't** find the corresponding **twilight** image。
- Dark_Zurich_train_anon/rgb_anon/train/**day**/GOPR0345/GOPR0345_frame_000276_rgb_anon.png
![GOPR0345_frame_000276_rgb_anon](https://user-images.githubusercontent.com/59300179/137316294-151b0e5b-59f1-45d8-b45f-7b7b6057984d.png)
- Dark_Zurich_train_anon/rgb_anon/train/**night**/GOPR0351/GOPR0351_frame_000172_rgb_anon.png
![GOPR0351_frame_000172_rgb_anon](https://user-images.githubusercontent.com/59300179/137316929-7a03b665-c8e1-487c-9e7d-14a5d74411bf.png)

**Comment by sakaridis** [comment]
Hello,
Unfortunately, we only provide pairwise correspondences between the twilight or nighttime set (as input) and the daytime set (as reference).
However, you can use the GPS annotations of the images in the daytime/twilight/nighttime sets, which are available in the `gps` directory of the Dark Zurich downloadable, in order to create arbitrary pairwise correspondences, e.g., nighttime -> twilight. After that, you can use these new correspondences together with nighttime -> daytime to construct the triplets you are interested in.

**Comment by creater-zq** [comment]
thanks! 


| |
张取
|
|
***@***.***
|
签名由网易邮箱大师定制
On 10/14/2021 ***@***.***> wrote：

Hello,
Unfortunately, we only provide pairwise correspondences between the twilight or nighttime set (as input) and the daytime set (as reference).
However, you can use the GPS annotations of the images in the daytime/twilight/nighttime sets, which are available in the gps directory of the Dark Zurich downloadable, in order to create arbitrary pairwise correspondences, e.g., nighttime -> twilight. After that, you can use these new correspondences together with nighttime -> daytime to construct the triplets you are interested in.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
